# Generated by Django 5.2 on 2025-05-08 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_taskassignee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'permissions': [('view_project_dashboard', 'Can view project dashboard'), ('manage_project_members', 'Can manage project members')]},
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='project',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
